
/* This file is auto generated by GetGitVersion.cmake and necessary for build dependencies */

#include "version.h"

#define _UPCXX_UTILS_VERSION_ "0.3.5"
#define _UPCXX_UTILS_BUILD_DATE "20230111_131515"
#define _UPCXX_UTILS_BRANCH ""

const char *UPCXX_UTILS_VERSION = _UPCXX_UTILS_VERSION_;
const char *UPCXX_UTILS_BUILD_DATE = _UPCXX_UTILS_BUILD_DATE;
const char *UPCXX_UTILS_VERSION_DATE = _UPCXX_UTILS_VERSION_ "-" _UPCXX_UTILS_BUILD_DATE;
const char *UPCXX_UTILS_BRANCH = _UPCXX_UTILS_BRANCH;
