#!/bin/bash

# 
# This file is autogenerated by GetGitVersion.cmake
#

ver=$(cat VERSION);
if [ -e .git ]
then
  GIT_EXECUTABLE=$(which git)

  base=$(${GIT_EXECUTABLE} describe --abbrev=0 --always)
  hash=$(${GIT_EXECUTABLE} describe --dirty --always)
  branch=$(${GIT_EXECUTABLE} rev-parse --abbrev-ref HEAD )

  # check if the latest tag is the same base VERSION
  if [ "${base}" != "v${ver}" ]
  then
    base=XXX_dummy_XXX # keep the whole tag
  fi

  tweak=
  if [ "${base}" != "${hash}" ]
  then
    tweak=$(echo $hash | sed 's/'$base'-//;')
  fi
  if [ -n "${tweak}" ]
  then
    echo "${ver}.${tweak}" "${branch}"
    exit
  fi
fi
echo "${ver}" "${branch}"
