
/* This file is auto generated by GetGitVersion.cmake and necessary for build dependencies */

#include "version.h"

#define _MHM2_VERSION_ "2.0.1.2"
#define _MHM2_BUILD_DATE "20230111_131515"
#define _MHM2_BRANCH ""

const char *MHM2_VERSION = _MHM2_VERSION_;
const char *MHM2_BUILD_DATE = _MHM2_BUILD_DATE;
const char *MHM2_VERSION_DATE = _MHM2_VERSION_ "-" _MHM2_BUILD_DATE;
const char *MHM2_BRANCH = _MHM2_BRANCH;
